name: Deploy to Production

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: ${{ github.event.inputs.environment || 'production' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      env:
        NODE_ENV: production
        
    - name: Create deployment package
      run: |
        tar -czf deployment.tar.gz build/ server.js package.json package-lock.json ecosystem.config.json
        
    - name: Upload deployment package
      uses: actions/upload-artifact@v4
      with:
        name: deployment-package
        path: deployment.tar.gz
        
    # Exemplo de deploy para servidor próprio via SSH
    - name: Deploy via SSH
      if: github.event.inputs.environment == 'production' || startsWith(github.ref, 'refs/tags/')
      run: |
        echo "🚀 Deploying to production server..."
        # Descomente e configure as linhas abaixo para deploy via SSH:
        #
        # - name: Setup SSH
        #   uses: webfactory/ssh-agent@v0.7.0
        #   with:
        #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        #
        # - name: Deploy to server
        #   run: |
        #     scp deployment.tar.gz user@server:/path/to/app/
        #     ssh user@server 'cd /path/to/app && tar -xzf deployment.tar.gz && pm2 restart ecosystem.config.json'
        
    # Exemplo de deploy para Vercel
    - name: Deploy to Vercel
      if: false # Mude para true se quiser usar Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        vercel-args: '--prod'
        
    - name: Notify success
      run: |
        echo "✅ Deployment to ${{ github.event.inputs.environment || 'production' }} completed successfully!"
